### ISSUE TITLE
Template/HTML part example

### ISSUE THREAD

**Issue by martinklaus** [milkcan/ionic-numberpicker#1]
To use the number picker a HTML part is necessary.
Can you please at a example like this:
`<ionic-timepicker input-obj="timePickerObject">
  <button class="button button-block button-positive overflowShow">
    <standard-time-meridian etime='timePickerObject.inputEpochTime'></standard-time-meridian>
  </button>
</ionic-timepicker>`

**Comment by mdridley** [comment]
Done. Added as step #5 in ReadMe. Thanks.
