### ISSUE TITLE
Reopen Number Picker give 0

### ISSUE THREAD

**Issue by martinklaus** [milkcan/ionic-numberpicker#2]
Wen you pick a number and close the picker. In next time the picker shows again 0 and not the select value.

I using to show the current value in the button this method:

`function numberPickerCallback(val,$scope) {
  if (typeof (val) === 'undefined') {
    console.log('Time not selected');
  } else {
    $scope.numberPickerObject.inputValue = val;
  }`

and this html:
`   <ionic-numberpicker input-obj="numberPickerObject">
      <button class="button button-positive order-button">
        {{ numberPickerObject.inputValue }}
      </button>
    </ionic-numberpicker>`

where is `{{ inputNumber }}` defined ?

**Comment by mdridley** [comment]
What does your numberPickerObject look like in the control? Are you seeing console output to show that the numberPickerCallback is indeed being called?

Example:
`var numberPickerCallback = function(val) {
        if (typeof(val) === 'undefined') {
          console.log('No number selected');
        } else {
          console.log('Selected number is: ', val);
          $scope.weight = val;
        }
      };

      $scope.numberPickerObject = {
        inputValue: $scope.weight,
        minValue: 0,
        maxValue: 20,
        step: 0.25,  //Optional
        format: 'DECIMAL',  //Optional
        titleLabel: 'Weight',  //Optional
        callback: function (val) {    //Mandatory
          numberPickerCallback(val);
        }
      };`
