### ISSUE TITLE
When opening a new window value is always 0

### ISSUE THREAD

**Issue by zocheyado** [milkcan/ionic-numberpicker#8]
So I am using everything based on the documentation and it all seems to work perfectly 

```
.controller('SettingsCtrl', function($scope, $stateParams) {
  $scope.numberPickerObject = {
    inputValue: 0, //Optional
    minValue: 0,
    maxValue: 15,
    format: "WHOLE",  //Optional - "WHOLE" or "DECIMAL"
    titleLabel: 'Number Picker',  //Optional
    setLabel: 'Set',  //Optional
    closeLabel: 'Close',  //Optional
    setButtonType: 'button-positive',  //Optional
    closeButtonType: 'button-stable',  //Optional
    callback: function (val) {    //Mandatory
      $scope.numberPickerObject.inputValue = val;
    }
  };
```

However whenever I hit "set" the value gets passed back, and I can save that value as a local value, scope value, console.log it etc and everything works fine. However, if I stay on the same page, and I then click the edit number button again it still comes up 0, instead of the number I had selected just moments ago. SO to try and fix this I made $scope.numberPickerObject.inputValue = val; and it seems to do nothing, any ideas?

**Comment by manojjkurup** [comment]
Zocheyado, Did you solve?? I am also having the same issue

**Comment by zocheyado** [comment]
No unfortunately I did not fix it properly, not sure if it is possible within the plugin. I did fix it however, I essentially take the number they input, then in the callback destroy the old instance of the number pick and create a new one with my new number. Works but it is very jenky.

**Comment by K1pavic** [comment]
@zocheyado  Until the pull request is merged you can just use my fork [here.](https://github.com/K1pavic/ionic-numberpicker/tree/64589f8a99a0a3c2ac2f5d5479309ff5f4a169c3)
You can download it and just replace the ionic-numberpicker.bundle.min.js file from the dist directory and use the code from your first comment.
